# Generated by Django 3.1.7 on 2021-03-11 15:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
